#server:
#  port: 8081
#
#Spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/HR-Department
#    password: password
#spring:
#  datasource:
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#welcome:
#  message: Welcome to Office Information Application !!!